### ISSUE TITLE
Compatibility with forum theme

### ISSUE THREAD

**Issue by momomok** [gaplo917/hkepc-ionic-reader#3]
When "show all subforums" is enabled (aka, 20 taps on 論壇坂塊), the app fails to read anything if the theme of HKEPC is not **HKEPC** / **使用默認** in [論壇個性化設定](http://www.hkepc.com/forum/memcp.php?action=profile&typeid=5)

Maybe add a warning to prompt users that this may happen?

**Comment by gaplo917** [comment]
@momomok Good suggestion
